In [2]:
# problem 1.3.1
import numpy as np
a = np.zeros(64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            a[i][j] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [3]:
# problem 1.3.2
a = np.arange(0, 5 * 5).reshape(5, 5)
for i in range(1, 5):
    for j in range(5):
        a[i][j] -= i * 5
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
# problem 1.3.3
a = np.random.random((5, 5, 5))
print(a)

[[[0.08050147 0.90379923 0.39078068 0.31079594 0.67253892]
  [0.01896981 0.61265905 0.01967843 0.12603762 0.77727188]
  [0.09835757 0.30189665 0.04566294 0.32010114 0.91260586]
  [0.61060941 0.35073108 0.15162965 0.64803029 0.01464759]
  [0.98990073 0.86554759 0.31790775 0.61705339 0.44248296]]

 [[0.05581986 0.54095595 0.1907765  0.2693583  0.82795303]
  [0.82975896 0.53497291 0.92621937 0.44656193 0.47021716]
  [0.37319329 0.14305636 0.36349942 0.64271745 0.57019015]
  [0.16738943 0.60616918 0.51609428 0.82564066 0.8874681 ]
  [0.66514387 0.72880461 0.95907079 0.47446224 0.94986766]]

 [[0.99961854 0.04217885 0.12232046 0.56100908 0.35147512]
  [0.1615714  0.12190663 0.26585702 0.00488875 0.62291753]
  [0.1199803  0.22945526 0.47507337 0.34769188 0.85192906]
  [0.4593214  0.90249279 0.25699198 0.02327546 0.18261865]
  [0.30392437 0.26669443 0.69944707 0.65574252 0.05983081]]

 [[0.90623113 0.44529436 0.66284498 0.81367619 0.29537574]
  [0.02483827 0.47540279 0.987124   0.43848683 0.8

In [5]:
# problem 1.3.4

# size x*y
x = 10
y = 10

a = np.zeros((x, y))
for i in range(x):
    for j in range(y):
        if i == 0 or i == y - 1 or j == 0 or j == x - 1:
            a[i][j] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
# problem 1.3.5
a = np.random.random(10)
print("original array:\n", a)
print("\nsorted array:\n", np.sort(a))
print("\nsorted backwards:\n", np.sort(a)[::-1])

original array:
 [0.81477177 0.59069233 0.19004593 0.28469819 0.56938791 0.27195856
 0.10286935 0.49657005 0.64684179 0.33468441]

sorted array:
 [0.10286935 0.19004593 0.27195856 0.28469819 0.33468441 0.49657005
 0.56938791 0.59069233 0.64684179 0.81477177]

sorted backwards:
 [0.81477177 0.64684179 0.59069233 0.56938791 0.49657005 0.33468441
 0.28469819 0.27195856 0.19004593 0.10286935]


In [7]:
# problem 1.3.6

# size x*y*z
x = 2
y = 3
z = 4

a = np.zeros((x, y, z))

print(a)
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
24
3


In [8]:
# problem 2.3.1
import pandas as pd

# coords
a = (0, 0)
b = (1, 1)

a = pd.Series(a)
b = pd.Series(b)

print(np.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2))

1.4142135623730951


In [9]:
# problem 2.3.2
url = "https://raw.githubusercontent.com/akmand/datasets/main/naval.csv"
data = pd.read_csv(url)

In [10]:
# problem 2.3.3
data

1   2          3         4         5        6        7         8  \
0      1.138   3    289.964  1349.489  6677.380    7.584    7.584   464.006   
1      2.088   6   6960.180  1376.166  6828.469   28.204   28.204   635.401   
2      3.144   9   8379.229  1386.757  7111.811   60.358   60.358   606.002   
3      4.161  12  14724.395  1547.465  7792.630  113.774  113.774   661.471   
4      5.140  15  21636.432  1924.313  8494.777  175.306  175.306   731.494   
...      ...  ..        ...       ...       ...      ...      ...       ...   
11929  5.140  15  21624.934  1924.342  8470.013  175.239  175.239   681.658   
11930  6.175  18  29763.213  2306.745  8800.352  245.954  245.954   747.405   
11931  7.148  21  39003.867  2678.052  9120.889  332.389  332.389   796.457   
11932  8.206  24  50992.579  3087.434  9300.274  438.024  438.024   892.945   
11933  9.300  27  72775.130  3560.400  9742.950  644.880  644.880  1038.411   

         9       10     11     12      13     14      15     16    17      y  
0      288  550.563  1.096  0.998   5.947  1.019   7.137  0.082  0.95  0.975  
1      288  581.658  1.331  0.998   7.282  1.019  10.655  0.287  0.95  0.975  
2      288  587.587  1.389  0.998   7.574  1.020  13.086  0.259  0.95  0.975  
3      288  613.851  1.658  0.998   9.007  1.022  18.109  0.358  0.95  0.975  
4      288  645.642  2.078  0.998  11.197  1.026  26.373  0.522  0.95  0.975  
...    ...      ...    ...    ...     ...    ...     ...    ...   ...    ...  
11929  288  628.950  2.087  0.998  10.990  1.027  23.803  0.471  1.00  1.000  
11930  288  658.853  2.512  0.998  13.109  1.031  32.671  0.647  1.00  1.000  
11931  288  680.393  2.982  0.998  15.420  1.036  42.104  0.834  1.00  1.000  
11932  288  722.029  3.594  0.998  18.293  1.043  58.064  1.149  1.00  1.000  
11933  288  767.595  4.531  0.998  22.464  1.052  86.067  1.704  1.00  1.000  

[11934 rows x 18 columns]

In [11]:
data.shape

(11934, 18)

In [12]:
data.describe()

1             2             3             4             5  \
count  11934.000000  11934.000000  11934.000000  11934.000000  11934.000000   
mean       5.166667     15.000000  27247.498685   2136.289256   8200.947312   
std        2.626388      7.746291  22148.613155    774.083881   1091.315507   
min        1.138000      3.000000    253.547000   1307.675000   6589.002000   
25%        3.144000      9.000000   8375.883750   1386.758000   7058.324000   
50%        5.140000     15.000000  21630.659000   1924.326000   8482.081500   
75%        7.148000     21.000000  39001.426750   2678.079000   9132.606000   
max        9.300000     27.000000  72784.872000   3560.741000   9797.103000   

                  6             7             8        9            10  \
count  11934.000000  11934.000000  11934.000000  11934.0  11934.000000   
mean     227.335768    227.335768    735.495446    288.0    646.215331   
std      200.495889    200.495889    173.680552      0.0     72.675882   
min        5.304000      5.304000    442.364000    288.0    540.442000   
25%       60.317000     60.317000    589.872750    288.0    578.092250   
50%      175.268000    175.268000    706.038000    288.0    637.141500   
75%      332.364750    332.364750    834.066250    288.0    693.924500   
max      645.249000    645.249000   1115.797000    288.0    789.094000   

                 11            12            13            14            15  \
count  11934.000000  1.193400e+04  11934.000000  11934.000000  11934.000000   
mean       2.352963  9.980000e-01     12.297123      1.029474     33.641261   
std        1.084770  2.533635e-13      5.337448      0.010390     25.841363   
min        1.093000  9.980000e-01      5.828000      1.019000      0.000000   
25%        1.389000  9.980000e-01      7.447250      1.020000     13.677500   
50%        2.083000  9.980000e-01     11.092000      1.026000     25.276500   
75%        2.981000  9.980000e-01     15.658000      1.036000     44.552500   
max        4.560000  9.980000e-01     23.140000      1.052000     92.556000   

                 16           17           y  
count  11934.000000  11934.00000  11934.0000  
mean       0.662440      0.97500      0.9875  
std        0.507132      0.01472      0.0075  
min        0.068000      0.95000      0.9750  
25%        0.246000      0.96200      0.9810  
50%        0.496000      0.97500      0.9875  
75%        0.882000      0.98800      0.9940  
max        1.832000      1.00000      1.0000

In [13]:
data.iloc[100:105]

1   2          3         4         5        6        7        8    9  \
100  2.088   6   6310.331  1354.347  6843.080   24.201   24.201  614.503  288   
101  3.144   9   8380.390  1386.764  7140.311   60.369   60.369  596.935  288   
102  4.161  12  14725.397  1547.472  7814.850  113.784  113.784  651.649  288   
103  5.140  15  21638.498  1924.331  8504.847  175.300  175.300  720.631  288   
104  6.175  18  29796.172  2307.284  8839.761  246.337  246.337  788.130  288   

          10     11     12      13     14      15     16    17      y  
100  577.215  1.305  0.998   7.074  1.019  20.679  0.272  0.95  0.986  
101  585.939  1.388  0.998   7.493  1.020  12.712  0.252  0.95  0.986  
102  612.065  1.655  0.998   8.907  1.022  17.640  0.349  0.95  0.986  
103  643.627  2.075  0.998  11.071  1.026  25.754  0.510  0.95  0.986  
104  673.935  2.497  0.998  13.205  1.030  34.959  0.692  0.95  0.986

In [14]:
data[data["2"] == 9]

1  2         3         4         5       6       7        8    9  \
2      3.144  9  8379.229  1386.757  7111.811  60.358  60.358  606.002  288   
11     3.144  9  8379.307  1386.758  7114.396  60.353  60.353  605.169  288   
20     3.144  9  8379.456  1386.759  7116.987  60.356  60.356  604.338  288   
29     3.144  9  8379.548  1386.759  7119.575  60.351  60.351  603.509  288   
38     3.144  9  8379.616  1386.760  7122.162  60.358  60.358  602.680  288   
...      ... ..       ...       ...       ...     ...     ...      ...  ...   
11891  3.144  9  8375.285  1386.735  7053.223  60.314  60.314  566.908  288   
11900  3.144  9  8375.342  1386.735  7055.723  60.315  60.315  566.142  288   
11909  3.144  9  8375.484  1386.736  7058.231  60.313  60.313  565.378  288   
11918  3.144  9  8375.563  1386.736  7060.734  60.318  60.318  564.615  288   
11927  3.144  9  8375.659  1386.737  7063.239  60.319  60.319  563.854  288   

            10     11     12     13     14      15     16    17      y  
2      587.587  1.389  0.998  7.574  1.020  13.086  0.259  0.95  0.975  
11     587.437  1.389  0.998  7.567  1.020  13.052  0.258  0.95  0.976  
20     587.286  1.389  0.998  7.559  1.020  13.018  0.258  0.95  0.977  
29     587.136  1.389  0.998  7.552  1.020  12.983  0.257  0.95  0.978  
38     586.986  1.388  0.998  7.544  1.020  12.949  0.256  0.95  0.979  
...        ...    ...    ...    ...    ...     ...    ...   ...    ...  
11891  573.824  1.392  0.998  7.445  1.021  11.550  0.229  1.00  0.996  
11900  573.683  1.392  0.998  7.438  1.021  11.517  0.228  1.00  0.997  
11909  573.542  1.392  0.998  7.431  1.021  11.484  0.227  1.00  0.998  
11918  573.400  1.392  0.998  7.424  1.021  11.452  0.227  1.00  0.999  
11927  573.260  1.391  0.998  7.416  1.021  11.419  0.226  1.00  1.000  

[1326 rows x 18 columns]

In [16]:
# problem 3.3.2 доделать
from sklearn import preprocessing
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
data = pd.read_csv(url)
scaler = preprocessing.MinMaxScaler
data

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]